FROM node:15

WORKDIR /usr/src/app

RUN rm -rf node_modules && rm -f package-lock.json && npm cache clean --force

COPY package*.json ./

RUN npm install --quiet

COPY . .

EXPOSE 3000

CMD [ "node", "index.js" ]